steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'POSTGRES_PASSWORD=mysecretpassword'
  - 'POSTGRES_USERNAME=postgres'
  - 'POSTGRES_DATABASE=votefwd'
  - 'POSTGRES_HOST=postgres'
  - 'POSTGRES_DB=votefwd'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'db:test']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'POSTGRES_PASSWORD=mysecretpassword'
  - 'POSTGRES_USERNAME=postgres'
  - 'POSTGRES_DATABASE=postgres'
  - 'POSTGRES_HOST=postgres'
  - 'POSTGRES_DB=postgres'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'db:migrate']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'POSTGRES_PASSWORD=mysecretpassword'
  - 'POSTGRES_USERNAME=postgres'
  - 'POSTGRES_DATABASE=votefwd'
  - 'POSTGRES_HOST=postgres'
  - 'POSTGRES_DB=votefwd'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run','test']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
