steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'POSTGRES_PASSWORD=mysecretpassword'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'db:test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run','test']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
