steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  env:
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'db:test']
  env:
  - 'POSTGRES_DB=postgres'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'db:migrate']
  env:
- name: 'gcr.io/cloud-builders/npm'
  args: ['run','test']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "This step only runs gcloud app deploy if this build was triggered by a push to master."
    if [ "$BRANCH_NAME" == "master" ] 
    then
      gcloud app deploy && echo "finished gcloud deploy"
    fi
options:
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'POSTGRES_PASSWORD=mysecretpassword'
    - 'POSTGRES_USERNAME=postgres'
    - 'POSTGRES_DATABASE=votefwd'
    - 'POSTGRES_HOST=postgres'
    - 'POSTGRES_DB=votefwd'
